---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group pipeline modules together for pull requests
      # "pipeline-submodules" is an arbitrary name
      pipeline-submodules:
        patterns:
          - "*/pipeline-Nextflow-config"
          - "*/pipeline-Nextflow-module"
          - "lib"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
