---
name: Generate Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: theboutroslab/tool-generate-docs@v1
